title: NetON 
description: "NetON Ethical Hacking Group Writeups"
author:
  name: "NetON"
  email: ""
  url: "https://netonehc.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "NetON"
year : "2020"
